
export const platforms = [
    { idPlatform: 6, name: 'PC', short: 'PC' },
    { idPlatform: 167, name: 'Sony PlayStation 5', short: 'PS5' },
    { idPlatform: 48, name: 'Sony PlayStation 4', short: 'PS4' },
    { idPlatform: 169, name: 'Microsoft Xbox Series X|S', short: 'XSX|S' },
    { idPlatform: 508, name: 'Nintendo Switch 2', short: 'NS2' },
    { idPlatform: 130, name: 'Nintendo Switch', short: 'NS' },
    { idPlatform: 3, name: 'Linux', short: 'Linux' },
    { idPlatform: 7, name: 'Sony PlayStation', short: 'PS' },
    { idPlatform: 8, name: 'Sony PlayStation 2', short: 'PS2' },
    { idPlatform: 9, name: 'Sony PlayStation 3', short: 'PS3' },
    { idPlatform: 165, name: 'Sony PlayStation VR', short: 'PS VR' },
    { idPlatform: 11, name: 'Microsoft Xbox', short: 'Xbox' },
    { idPlatform: 12, name: 'Microsoft Xbox 360', short: 'Xbox 360' },
    { idPlatform: 14, name: 'Apple Mac', short: 'Mac' },
    { idPlatform: 4, name: 'Commodore 64', short: 'C64' },
    { idPlatform: 15, name: 'Commodore 128', short: 'C128' },
    { idPlatform: 18, name: 'Nintendo Entertainment System', short: 'NES' },
    { idPlatform: 19, name: 'Super Nintendo', short: 'SNES' },
    { idPlatform: 20, name: 'Nintendo DS', short: 'DS' },
    { idPlatform: 21, name: 'Nintendo GameCube', short: 'GC' },
    { idPlatform: 29, name: 'Sega Mega Drive / Genesis', short: 'MD' },
    { idPlatform: 30, name: 'Sega 32X', short: '32X' },
    { idPlatform: 32, name: 'Sega Saturn', short: 'Saturn' },
    { idPlatform: 35, name: 'Sega Game Gear', short: 'GG' },
    { idPlatform: 37, name: 'Nintendo 3DS', short: '3DS' },
    { idPlatform: 38, name: 'Sony PlayStation Portable', short: 'PSP' },
    { idPlatform: 39, name: 'Apple iOS', short: 'iOS' },
    { idPlatform: 46, name: 'Sony PlayStation Vita', short: 'PS Vita' },
    { idPlatform: 49, name: 'Microsoft Xbox One', short: 'Xbox One' },
    { idPlatform: 59, name: 'Atari 2600', short: 'A2600' },
    { idPlatform: 60, name: 'Atari 7800', short: 'A7800' },
    { idPlatform: 61, name: 'Atari Lynx', short: 'Lynx' },
    { idPlatform: 62, name: 'Atari Jaguar', short: 'Jaguar' },
    { idPlatform: 63, name: 'Atari ST', short: 'ST' },
    { idPlatform: 64, name: 'Sega Master System', short: 'SMS' },
    { idPlatform: 65, name: 'Atari 8-bit', short: 'A8bit' },
    { idPlatform: 66, name: 'Atari 5200', short: 'A5200' },
    { idPlatform: 71, name: 'Commodore VIC-20', short: 'VIC-20' },
    { idPlatform: 75, name: 'Apple II', short: 'Apple II' },
    { idPlatform: 78, name: 'Sega CD', short: 'SCD' },
    { idPlatform: 90, name: 'Commodore PET', short: 'PET' },
    { idPlatform: 93, name: 'Commodore 16', short: 'C16' },
    { idPlatform: 94, name: 'Commodore Plus/4', short: 'Plus/4' },
    { idPlatform: 158, name: 'Commodore CDTV', short: 'CDTV' },
    { idPlatform: 159, name: 'Nintendo DSi', short: 'DSi' },
    { idPlatform: 339, name: 'Sega Pico', short: 'Pico' },
    { idPlatform: 390, name: 'Sony PlayStation VR2', short: 'PS VR2' },
    { idPlatform: 410, name: 'Atari Jaguar CD', short: 'Jag CD' },
    { idPlatform: 482, name: 'Sega CD 32X', short: 'CD32X' },
]

export const genres = [
    { idGenre: 36, name: 'MOBA' },
    { idGenre: 33, name: 'Аркада' },
    { idGenre: 11, name: 'В реальном времени' },
    { idGenre: 34, name: 'Визуальная новелла' },
    { idGenre: 26, name: 'Викторина' },
    { idGenre: 9, name: 'Головоломка' },
    { idGenre: 10, name: 'Гонки' },
    { idGenre: 32, name: 'Инди' },
    { idGenre: 35, name: 'Карточная' },
    { idGenre: 2, name: 'Квест' },
    { idGenre: 7, name: 'Музыка' },
    { idGenre: 30, name: 'Пинбол' },
    { idGenre: 8, name: 'Платформер' },
    { idGenre: 16, name: 'Пошаговая' },
    { idGenre: 31, name: 'Приключение' },
    { idGenre: 12, name: 'Ролевая' },
    { idGenre: 13, name: 'Симулятор' },
    { idGenre: 25, name: 'Слэшер' },
    { idGenre: 14, name: 'Спортивная' },
    { idGenre: 15, name: 'Стратегия' },
    { idGenre: 24, name: 'Тактика' },
    { idGenre: 4, name: 'Файтинг' },
    { idGenre: 5, name: 'Шутер' }
]

export const brands = [
    { idBrand: 5, name: 'Apple' },
    { idBrand: 6, name: 'Atari' },
    { idBrand: 7, name: 'Commodore' },
    { idBrand: 2, name: 'Microsoft' },
    { idBrand: 3, name: 'Nintendo' },
    { idBrand: 4, name: 'Sega' },
    { idBrand: 1, name: 'Sony' }
]

export const themes = [
    { idTheme: 41, name: '4X стратегия' },
    { idTheme: 28, name: 'Бизнес' },
    { idTheme: 39, name: 'Война' },
    { idTheme: 21, name: 'Выживание' },
    { idTheme: 43, name: 'Детектив/Тайна' },
    { idTheme: 40, name: 'Для вечеринки' },
    { idTheme: 42, name: 'Для взрослых (18+)' },
    { idTheme: 35, name: 'Для детей (6+)' },
    { idTheme: 32, name: 'Документальный' },
    { idTheme: 31, name: 'Драма' },
    { idTheme: 22, name: 'Историческая' },
    { idTheme: 27, name: 'Комедия' },
    { idTheme: 18, name: 'Научная фантастика' },
    { idTheme: 34, name: 'Обучающая' },
    { idTheme: 38, name: 'Открытый мир' },
    { idTheme: 33, name: 'Песочница' },
    { idTheme: 44, name: 'Романтика' },
    { idTheme: 23, name: 'Стелс' },
    { idTheme: 20, name: 'Триллер' },
    { idTheme: 17, name: 'Фэнтези' },
    { idTheme: 19, name: 'Хоррор' },
    { idTheme: 1, name: 'Экшн' }
]

export const modes = [
    { idMode: 5, name: 'MMO' },
    { idMode: 6, name: 'Баттл Рояль' },
    { idMode: 3, name: 'Кооперативная' },
    { idMode: 2, name: 'Мультиплеер' },
    { idMode: 1, name: 'Одиночная' },
    { idMode: 4, name: 'Разделённый экран' }
]

export const perspectives = [
    { idPerspective: 1, name: 'От первого лица' },
    { idPerspective: 2, name: 'От третьего лица' },
    { idPerspective: 3, name: 'Сверху/Изометрия' },
    { idPerspective: 4, name: 'Вид сбоку' },
    { idPerspective: 5, name: 'Текст' },
    { idPerspective: 6, name: 'Аудио' },
    { idPerspective: 7, name: 'VR' }
]

export const yearOptions = [
    { value: '2026' },
    { value: '2025' },
    { value: '2024' },
    { value: '2023' },
    { value: '2022' },
    { value: '2021' },
    { value: '2020' },
    { value: '2019' },
    { value: '2018' },
    { value: '2017' },
    { value: '2016' },
    { value: '2015' },
    { value: '2014' },
    { value: '2013' },
    { value: '2012' },
    { value: '2011' },
    { value: '2010' },
    { value: '2009' },
    { value: '2008' },
    { value: '2007' },
    { value: '2006' },
    { value: '2005' },
    { value: '2004' },
    { value: '2003' },
    { value: '2002' },
    { value: '2001' },
    { value: '2000' },
    { value: '1995-2000' },
    { value: '1990-1995' }
]